name: Build and Sign

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.SIGNING_CERT_BASE64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "LetonSoft.pfx"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      
    - name: Build
      run: |
        # 显示图标文件是否存在
        Write-Host "Checking icon file..."
        if (Test-Path "NetSpeedTray/Resources/icon.ico") {
            Write-Host "Icon file exists"
        } else {
            Write-Host "Icon file not found"
        }
        
        # 编译
        dotnet publish NetSpeedTray/NetSpeedTray.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -v detailed
        
    - name: Sign
      run: |
        $certificatePath = Join-Path -Path (Get-Location) -ChildPath "LetonSoft.pfx"
        & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign /f $certificatePath /p "${{ secrets.SIGNING_CERT_PASSWORD }}" /fd SHA256 /t http://timestamp.digicert.com "NetSpeedTray/bin/Release/net6.0-windows/win-x64/publish/NetSpeedTray.exe"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: NetSpeedTray/bin/Release/net6.0-windows/win-x64/publish/NetSpeedTray.exe